# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-15 21:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booker', '0002_adminuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('vso', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('is_org_admin', models.BooleanField(default=False)),
                ('is_group_admin', models.BooleanField(default=False)),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('groups', models.ManyToManyField(null=True, to='booker.Group')),
                ('organizations', models.ManyToManyField(null=True, to='booker.Organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user_name',
        ),
        migrations.DeleteModel(
            name='AdminUser',
        ),
        migrations.AddField(
            model_name='organization',
            name='admins',
            field=models.ManyToManyField(null=True, to='booker.UserProfile'),
        ),
        migrations.AddField(
            model_name='group',
            name='admins',
            field=models.ManyToManyField(to='booker.UserProfile'),
        ),
        migrations.AddField(
            model_name='building',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booker.Organization'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booker.UserProfile'),
        ),
    ]
