# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-15 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0003_auto_20160215_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, to='booker.Group'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='organizations',
            field=models.ManyToManyField(blank=True, null=True, to='booker.Organization'),
        ),
    ]
