# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-17 22:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0003_auto_20160417_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_group_admin',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_org_admin',
        ),
    ]
