# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-07 05:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0006_auto_20160307_0535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='organization',
        ),
    ]
