# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-18 08:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0006_auto_20160307_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='nres',
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booker.Group'),
        ),
    ]
