# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-07 05:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0007_remove_building_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='organization',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='booker.Organization'),
            preserve_default=False,
        ),
    ]
