# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-18 06:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0008_building_organization'),
        ('booker', '0007_reservation_group'),
    ]

    operations = [
    ]
