# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-18 07:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0012_auto_20160318_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='nres',
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booker.Group'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booker.UserProfile'),
        ),
    ]
