# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-18 07:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0013_auto_20160318_0708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='group',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
    ]
