# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-18 07:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0015_auto_20160318_0709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='nres',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='organizations',
        ),
    ]
